mode: 'train' # 'eval' 'test' 'finetune'
dataset: 'Clotho'  # 'Clotho'
sos_token: Yes
keywords: Yes
num_keywords: 5

wav:
  sr: 32000
  window_size: 1024
  hop_length: 320
  mel_bins: 64
  fmin: 50
  fmax: 14000

decoder:
  decoder_only: Yes
  nhead: 4
  nhid: 128
  nlayers: 2
  dropout: 0.2
  dim_feedforward: 2048
  activation: 'gelu'

encoder:
  model: 'Cnn10'
  freeze: Yes
  pretrained: Yes

word_embedding:
  pretrained: Yes
  freeze: Yes

hugging_face:
  pretrain: Yes

data:
  batch_size: 32
  num_workers: 8

training:
  label_smoothing: Yes
  spec_augmentation: Yes
  epochs: 30
  lr: !!float 1e-3
  clip_grad: 2
  seed: 20

path:
  vocabulary: 'data/{}/pickles/words_list.p'
  encoder: 'pretrained_models/audio_encoder/'
  word2vec: 'pretrained_models/word2vec/w2v_all_vocabulary.model'
  model: ''

rl:
  epochs: 50
  model: "outputs/DCASE/keywords_finetune_data_Clotho_seed_30/model/best_model.pth"
  lr: !!float 1e-4
